# Generated by Django 4.1.5 on 2023-02-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Numero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=200)),
                ("ingreso", models.IntegerField()),
                ("egreso", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
